version: '2'
services:
    tasks-app:
        image: tasks
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tasks-postgresql:5432/tasks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tasks-postgresql:
        extends:
            file: postgresql.yml
            service: tasks-postgresql
